#!/usr/bin/bash
sudo apt update -y
sudo apt install apache2 -y
sudo systemctl start apache2
sudo systemctl enable apache2
sudo chmod o+w -R /var/www/
instancePrivateIP=http://169.254.169.254/latest/meta-data/local-ipv4
sudo curl ${instancePrivateIP} > /var/www/html/index.html
